# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DELIVERY', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state_name',
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DELIVERY.State'),
            preserve_default=False,
        ),
    ]
