# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELIVERY', '0003_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='address1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='address2',
            field=models.TextField(max_length=200),
        ),
    ]
