# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_title', models.CharField(max_length=150)),
                ('rest_created', models.DateTimeField(auto_now_add=True)),
                ('rest_image', models.ImageField(default='default.png', upload_to='restaurant_image')),
                ('rest_desc', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=50)),
                ('food_cuisine', models.CharField(max_length=50)),
                ('food_image', models.ImageField(default='food.png', upload_to='food_images')),
                ('food_price', models.CharField(max_length=50)),
                ('food_Description', models.TextField(max_length=200)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTAURANT.Add_Restaurant')),
            ],
        ),
    ]
