# Generated by Django 2.1.3 on 2019-04-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_restaurant',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='add_restaurant',
            name='locality',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='add_restaurant',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
