# Generated by Django 2.1.3 on 2019-04-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANT', '0002_auto_20190423_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_restaurant',
            name='rest_desc',
            field=models.TextField(max_length=1000),
        ),
    ]
