# Generated by Django 2.1.3 on 2019-04-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RESTAURANT', '0003_auto_20190423_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_restaurant',
            name='rest_author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
